//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public partial class nyomtatvanyok {
    
    /// <remarks/>
    public csomaginformacio csomaginformacio;
    
    /// <remarks/>
    public abev abev;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("nyomtatvany")]
    public nyomtatvany[] nyomtatvany;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public partial class csomaginformacio {
    
    /// <remarks/>
    public muvelet muvelet;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool muveletSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public enum muvelet {
    
    /// <remarks/>
    importxkr,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public partial class abev {
    
    /// <remarks/>
    public int hibakszama;
    
    /// <remarks/>
    public string hash;
    
    /// <remarks/>
    public string programverzio;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public partial class nyomtatvany {
    
    /// <remarks/>
    public nyomtatvanyinformacio nyomtatvanyinformacio;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("mezo", IsNullable=false)]
    public mezo[] mezok;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public partial class nyomtatvanyinformacio {
    
    /// <remarks/>
    public string nyomtatvanyazonosito;
    
    /// <remarks/>
    public string nyomtatvanyverzio;
    
    /// <remarks/>
    public adozo adozo;
    
    /// <remarks/>
    public albizonylatazonositas albizonylatazonositas;
    
    /// <remarks/>
    public idoszak idoszak;
    
    /// <remarks/>
    public string megjegyzes;
    
    /// <remarks/>
    public string datfile;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public partial class adozo {
    
    /// <remarks/>
    public string nev;
    
    /// <remarks/>
    public string adoszam;
    
    /// <remarks/>
    public string adoazonosito;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public partial class albizonylatazonositas {
    
    /// <remarks/>
    public string megnevezes;
    
    /// <remarks/>
    public string azonosito;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public partial class munkavallalo {
    
    /// <remarks/>
    public string nev;
    
    /// <remarks/>
    public string adoazonosito;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public partial class idoszak {
    
    /// <remarks/>
    public string tol;
    
    /// <remarks/>
    public string ig;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public partial class mezo {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string eazon;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.apeh.hu/abev/nyomtatvanyok/2005/01", IsNullable=false)]
public partial class mezok {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mezo")]
    public mezo[] mezo;
}
